### ISSUE TITLE
Compatibility with VS2017

### ISSUE THREAD

**Issue by fraguada** [MISoftware/HtmlView#1]
Works well in VS 2015, would be great if it also worked for VS 2017.  I tried to update it myself following https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017 but I've never done anything VSIX related, I don't think I've modified the project correctly.  I do get it to install in VS 2017 after adding something to the prerequisites, but get some errors on starting a project with HtmlView On.

**Comment by midiway** [comment]
yep, have to find time to port it

**Comment by Hcyan-H** [comment]
I saw you start to compatible VS2017 in the code, I cloned the latest code, but I can't run it in VS2017, the preconditions prevent me. but I've never done anything VSIX related also.

**Comment by midiway** [comment]
Yeah. It is pretty complex stuff.
I 'm stuck in the script that packs all CEF binaries inside the .VSIX 🤕 
Will try to take a look at it on this weekend

**Comment by midiway** [comment]
Hey guys, now it should work in VS2017!
Problem is, I am unable to upload it to VS marketplace because it gives me error when uploading... file is too big.

But I upload latest build to the repo, get it here: https://github.com/MISoftware/HtmlView/blob/master/ReleaseInfo/HtmlView.vsix

**Comment by Hcyan-H** [comment]
Hey guys, thank u for ur update! i still can't install the vsix, because my Visual Studio Version is Enterprise. So this is the problem?

**Comment by Hcyan-H** [comment]
![snipaste_2018-05-08_17-01-48](https://user-images.githubusercontent.com/38110513/39748018-8621349c-52e1-11e8-9e47-46a25bdb17aa.jpg)

**Comment by midiway** [comment]
oh GOD, try again plz

I updated the .VSIX manifest to support VS enterprise

**Comment by Hcyan-H** [comment]
still can't install . the problem it's same.
Unable to install extensions for this product due to unresolved prerequisite issues.

![file](https://user-images.githubusercontent.com/38110513/39823688-25a0355a-53e0-11e8-96d8-cff4f4e2d30b.jpg)

**Comment by Hcyan-H** [comment]
![myvsversion](https://user-images.githubusercontent.com/38110513/39823989-d64b3152-53e0-11e8-9d12-45d2d558be50.jpg)

This is my Visual Studio version.

**Comment by midiway** [comment]
PLz, try again https://github.com/MISoftware/HtmlView/blob/master/ReleaseInfo/HtmlView.vsix

**Comment by Hcyan-H** [comment]
sorry , I still can't install.

**Comment by midiway** [comment]
Too bad.
I just successfully installed it in a VM with VS Enterprise...
No errors.

No idea what is causing this.
You downloaded again from https://github.com/MISoftware/HtmlView/blob/master/ReleaseInfo/HtmlView.vsix
?

**Comment by Hcyan-H** [comment]
yes, the problem is Unable to install extensions for this product due to unresolved prerequisite issues

**Comment by midiway** [comment]
mmm, our only hope is to watch VSIXInstaller.exe log files.
Open a CMD prompt, CD to the folder where you downloaded HtmlView.vsix, and run:
`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe" /log:installLog.txt HtmlView.vsix`

Then open the log file with:
`notepad %TEMP%/installLog.txt`

**Comment by Hcyan-H** [comment]
[installLog.txt](https://github.com/MISoftware/HtmlView/files/2023082/installLog.txt)

Hi, my friend, i got some error info : The prerequisite for the system component version does not match the installed version .

some log char it's chinese.

**Comment by Hcyan-H** [comment]
![sp20180521_232459_708](https://user-images.githubusercontent.com/38110513/40315533-3aa0bd9a-5d4e-11e8-8a21-4c358570f801.png)

I try to update my visual studio version and try agin.

**Comment by Hcyan-H** [comment]
![sp20180521_234516_272](https://user-images.githubusercontent.com/38110513/40316482-13d8024c-5d51-11e8-8c4e-b664daf50424.png)

Ok now, When I've updated it, I can install . hahah the before version is 15.3.4 , now is 15.7.1

**Comment by Hcyan-H** [comment]
![sp20180521_234931_231](https://user-images.githubusercontent.com/38110513/40316674-a4a21272-5d51-11e8-852c-684784251d9a.png)

i have a question. how to change background-color configuration.

**Comment by midiway** [comment]
Mmm, the background really should be white...
In the meatime just use CSS
```
html { background: white; }
```

What do you mean by..

> if can run it on mvc or any other web development. It will be more perfect. like mobile web development.

?

**Comment by midiway** [comment]
Fixed! Background is always white now.
